import type { RcmDashboardSnapshot } from "../services/workqueueQueryService";

export const mockDashboardSnapshot: RcmDashboardSnapshot = {
  workqueueSummary: {
    totalOpen: 7,
    byPriority: {
      urgent: 1,
      high: 2,
      normal: 4,
    },
    byWorkType: {
      eligibility_issue: 2,
      claim_batch_ready: 1,
    },
  },
  workqueueItems: [
    {
      id: "wq-eligibility-1",
      domain: "eligibility",
      workType: "eligibility_issue",
      status: "open",
      priority: "urgent",
      title: "Inactive coverage",
      description: "Client coverage needs verification before claim release.",
      sourceObjectType: "eligibility",
      sourceObjectId: "eligibility-1",
      assignedToUserId: null,
      dueAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      context: {},
    },
    {
      id: "wq-charge-1",
      domain: "charge_capture",
      workType: "documentation_missing",
      status: "open",
      priority: "high",
      title: "Missing signed note",
      description: "A charge is blocked because the clinical note is not signed.",
      sourceObjectType: "charge",
      sourceObjectId: "charge-1",
      assignedToUserId: null,
      dueAt: null,
      createdAt: new Date().toISOString(),
      context: {},
    },
  ],
  charges: [
    {
      id: "charge-1",
      tab: "documentation_missing",
      status: "captured",
      dateOfService: "2026-06-30",
      clientId: "Client A",
      providerId: "Provider A",
      appointmentId: "appointment-1",
      cptCode: "90837",
      diagnosisCodes: ["F41.1"],
      totalCharge: 150,
      blockers: ["Signed note missing"],
      actionNeeded: "Get signed note",
    },
    {
      id: "charge-2",
      tab: "ready_for_review",
      status: "ready_for_claim",
      dateOfService: "2026-06-30",
      clientId: "Client B",
      providerId: "Provider B",
      appointmentId: "appointment-2",
      cptCode: "90834",
      diagnosisCodes: ["F32.1"],
      totalCharge: 125,
      blockers: [],
      actionNeeded: "Review and approve",
    },
  ],
  claims: [
    {
      id: "claim-1",
      status: "validation_failed",
      clientId: "Client A",
      payerProfileId: "Payer A",
      renderingProviderId: "Provider A",
      totalCharge: 150,
      patientResponsibility: 20,
      payerResponsibility: 130,
      serviceDate: "2026-06-30",
      currentBatchId: null,
      actionNeeded: "Fix claim validation errors",
    },
    {
      id: "claim-2",
      status: "ready_for_batch",
      clientId: "Client B",
      payerProfileId: "Payer B",
      renderingProviderId: "Provider B",
      totalCharge: 125,
      patientResponsibility: 0,
      payerResponsibility: 125,
      serviceDate: "2026-06-30",
      currentBatchId: null,
      actionNeeded: "Add to batch",
    },
  ],
};
